### ISSUE TITLE
Building of RPM packages fails

### ISSUE THREAD

**Issue by bms8197** [OpenNebula/packages#123] opened 2020-02-18 06:59 UTC
Following your documentation from GitHub:
```
virt1 opt # tar -czf opennebula-5.10.2.tar.gz opennebula-5.10.2/
virt1 opt # cd packages/
virt1 packages # ./centos7.sh ../opennebula-5.10.2.tar.gz
***** Prepare sources
cp: cannot stat ‘/tmp/opennebula-5.10.2.tar.gz’: No such file or directory
```
I've managed to fix this and continue by copying opennebula-5.10.2.tar.gz to /tmp folder and re-run the build process. This step is not mentioned on the Readme file on your GitHub.
```
virt1 packages # cp ../opennebula-5.10.2.tar.gz /tmp/opennebula-5.10.2.tar.gz
virt1packages # ./centos7.sh ../opennebula-5.10.2.tar.gz
***** Prepare sources
```

**Comment by loveshack** [comment] 2020-02-27 16:24
Part of the problem is that the readlink in the build script is done after cd'ing to /tmp, so you can't use a relative path as in the instructions.

Also the source tarball name and its top-level directory need to to be changed when re-packing it after building the man pages, as in https://forum.opennebula.org/t/build-opennebula-5-10-2-from-source/8052/24

I could supply fixes for either the instructions or the build script, but I don't know what the intention is, i.e. what to change.

**Comment by ospalax** [comment] 2020-04-29 17:20
This should be fixed in this [PR](https://github.com/OpenNebula/packages/pull/145)

**Closed by ospalax** 2020-04-29 17:20 UTC
Labels: Community, Status: Accepted, Type: Bug
